# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.student_grades import StudentGrades
from swagger_server import util


class Student(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, first_name: str=None, last_name: str=None, grades: StudentGrades=None):  # noqa: E501
        """Student - a model defined in Swagger

        :param first_name: The first_name of this Student.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Student.  # noqa: E501
        :type last_name: str
        :param grades: The grades of this Student.  # noqa: E501
        :type grades: StudentGrades
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'grades': StudentGrades
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'grades': 'grades'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._grades = grades

    @classmethod
    def from_dict(cls, dikt) -> 'Student':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Student of this Student.  # noqa: E501
        :rtype: Student
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Student.


        :return: The first_name of this Student.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Student.


        :param first_name: The first_name of this Student.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Student.


        :return: The last_name of this Student.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Student.


        :param last_name: The last_name of this Student.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def grades(self) -> StudentGrades:
        """Gets the grades of this Student.


        :return: The grades of this Student.
        :rtype: StudentGrades
        """
        return self._grades

    @grades.setter
    def grades(self, grades: StudentGrades):
        """Sets the grades of this Student.


        :param grades: The grades of this Student.
        :type grades: StudentGrades
        """

        self._grades = grades
